### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by tdorey** [cogdog/tru-collector#1]
Hi Alan,

I don't think the preview in the collector tool is working. I've noticed this before, but am finally getting around to logging it as an issue. When you click preview now in the form you get
![image](https://user-images.githubusercontent.com/18656532/27019369-e0abf1f8-4eec-11e7-83bb-e8e54a125751.png)

**Comment by cogdog** [comment]
That's a real bug, thanks. It's a small CSS fix, so you can just replace 

`tru-collector/style.css`

with the one at 

https://github.com/cogdog/tru-collector/blob/master/style.css

or just add to your CSS, right after:

```
/* no images content area of single posts (hides submissions by email) */
.single-post .post-content img {
    display: none;
}
```

add this:

/* show featured image in forms */
#featurethumb {
    display: initial;
}

It can be seen working as it should at http://splot.ca/collector/collect/
