### ISSUE TITLE
TRU Collector in not coming with default theme on install

### ISSUE THREAD

**Issue by floatingtim** [cogdog/tru-collector#11]
The Fukasawa theme did not come with install.  I was able to pull the theme from a repair process that Wordpress presented to me.

**Comment by cogdog** [comment]
Hi Tim. Do you mean the installing of the theme directly from a GitHub download? Parent themes always need to be installed separately, see https://github.com/cogdog/tru-collector#installing-tru-collector-from-scratch

If you are referring to the Reclaim Hosting version, that's different. I was pretty sure the Installatron script did this, bu may need to check. I am trying to learn how to update those installers, but have not learned enough yet.

**Comment by floatingtim** [comment]
Yes, I was reporting through the Installatron TRU Collector.  I'm happy to look into how those can be updated, as well. Maybe I can be useful.

**Comment by cogdog** [comment]
I've messaged Reclaim Support, both these themes need updates to these release versions. I don't have access to the scripts

https://github.com/cogdog/truwriter/releases/tag/v3.27
https://github.com/cogdog/tru-collector/releases/tag/v2.44
