### ISSUE TITLE
Genericons not showing in theme

### ISSUE THREAD

**Issue by mhawksey** [cogdog/tru-collector#2]
So I had a problem with the sidebar menu. I noticed on active pages a genericon was used to put a cross next to the list item. On my install (WP 4.9.2)  the Genericon wasn't found. I checked the master and child theme and noticed Genericons don't appear to be packaged with it. My quick fix was to install the [Genericon'd plugin](https://en-gb.wordpress.org/plugins/genericond/). Should the icon font be included with this theme, or should I be opening a ticket on Fukasawa theme?

[Loving the work!]

**Comment by cogdog** [comment]
No, that was my mistake. I notice the Genericon font was in there but I could not figure out where it was used, I thought it was an artifact. Now I need to put it back, thanks.

**Comment by cogdog** [comment]
Done, thanks Martin.
