### ISSUE TITLE
Collector rotating images uploaded in portrait orientation

### ISSUE THREAD

**Issue by cmadland** [cogdog/tru-collector#4]
Ran a little test at pics.madland.ca and noticed that images uploaded from iphone in portrait orientation are rotated 90 degrees and displayed in landscape. Can't see any settings in the dashboard related to this. not sure where to look in the theme files.

Any suggestions?

**Comment by cogdog** [comment]
It's a bit of a mess to deal with, camera phones store rotation info in EXIF data, so what you are seeing is the original image. Here's a little background https://photowebo.com/wordpress-photos-sideways/ and looks like something WP may evolve into core. Before I fiddle with some patchy theme code, you might give this plugin a try

https://wordpress.org/plugins/ios-images-fixer/

I will try and test myself.

**Comment by cogdog** [comment]
Success, the plugin works. It's portrait mode photos which show up rotated- I just did a series of before and after plugin install tests in TRU Collector demo

http://splot.ca/collector/ 

Before http://splot.ca/collector/486/
After http://splot.ca/collector/489/

![rotate-test](https://user-images.githubusercontent.com/463038/41542220-b552aaba-72d1-11e8-9ea1-7d3007d49083.jpg)

The plugin gas a feature to process existing items in your library.

**Comment by cmadland** [comment]
Awesome, thanks! I’ll give it a go.

Colin Madland
http://madland.ca
@colinmadland

*Sent from mobile, please excuse brevity and typos.

On Jun 18, 2018, at 7:30 AM, Alan Levine <notifications@github.com<mailto:notifications@github.com>> wrote:


Success, the plugin works. It's portrait mode photos which show up rotated- I just did a series of before and after plugin install tests in TRU Collector demo

http://splot.ca/collector/

Before http://splot.ca/collector/486/
After http://splot.ca/collector/489/

[rotate-test]<https://user-images.githubusercontent.com/463038/41542220-b552aaba-72d1-11e8-9ea1-7d3007d49083.jpg>

The plugin has a feature to process existing items in your library. Let me know how it works for you

**Comment by cmadland** [comment]
Works like a charm! Thanks again!
